<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>sql</string>
        <string>ddl</string>
        <string>dml</string>
        <string>pks</string>
        <string>pkb</string>
    </array>
    <key>name</key>
    <string>PL/SQL Custom (Oracle)</string>
    <key>patterns</key>
    <array>
        <!--begin customization-->
        <dict>
            <key>match</key>
            <string>(?i)\b(self|column_value)\b</string>
            <key>name</key>
            <string>constant.language.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(\d+(\.\d+)?|\d+(\.\d+)?[GgMmKk]{1})\b</string>
            <key>name</key>
            <string>constant.numeric.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(forall)\b</string>
            <key>name</key>
            <string>keyword.control.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(bitand|bitor|bitxor|%(savepoint)|regexp_replace)\b</string>
            <key>name</key>
            <string>support.function.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(p(o|io)?_[-a-z0-9_]+)\b</string>
            <key>name</key>
            <string>variable.parameter.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b([lv]_[-a-z0-9_]+)\b</string>
            <key>name</key>
            <string>variable.other.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b((c|gc|k)_[-a-z0-9_]+)\b</string>
            <key>name</key>
            <string>constant.other.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(autoextend|body|connect|create|datafile|default|extent\s+management|flashback|(global\s+)?query\s+rewrite|invisible|job|local|logging|maxsize|next|on\s+commit|(preserve|delete)\s+rows|quota(\s+unlimited)?|role|segment|session|size|tablespace|uniform|virtual|((global|private)\s+temporary)|(authid|bequeath)\s+(current_user|definer)|generated\s+(always|by\s+default|on\s+null)\s+as\s+identity|(constructor\s+|static\s+|(map\s+)?member\s+)?(function\s+|procedure\s+)|result|object|materialized\s+view\s+log|(public\s+)?database\s+link|identified\s+by)\b</string>
            <key>name</key>
            <string>keyword.other.ddl.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(to|(public\s+)?synonym|(no)?logging|parallel|refresh\s+(fast|complete|force)|on\s+(demand|commit)|build\s+(immediate|deferred)|index(\s+by)?|dual|within(\s+group)?|errors\s+(into|reject\s+limit)?|truncate|multiset(\s+except|intersect|union)?|including\s+new|cascade|byte|option|disable|modify|value|execute)\b</string>
            <key>name</key>
            <string>keyword.other.sql.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(show\s+errors|off)\b</string>
            <key>name</key>
            <string>keyword.other.sqlplus.oracle</string>
        </dict>
        <!--
        support.class.user-defined.oracle
        support.constant.user-defined.oracle
        support.variable.user-defined.oracle
        support.type.user-defined.oracle
        -->
        <dict>
            <key>comment</key>
            <string>Highlight dynamic performance views and sys stuff</string>
            <key>match</key>
            <string>(?i)\b(v_?\$\w*|sys\.?\w+)\b</key>
            <key>name</key>
            <string>support.class.oracle</string>
        </dict>
        <dict>
            <!-- Database links -->
            <key>match</key>
            <string>(?i)((?<!@)@\w+)\b</string>
            <key>name</key>
            <string>support.constant.user-defined.oracle</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>support.class.oracle</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?i)\b((dbms|utl|owa|apex)_\w+\.([\w\$]+))\b</string>
            <key>name</key>
            <string>support.function.oracle</string>
        </dict>
        <dict>
            <key></key>
            <string>Overrides. Do not highlight these</string>
            <key>match</key>
            <string>(?i)\b(\.log|log\.|\.name|language|java|c|pi_\w+|[\.\$]sql)\b</string>
            <key>name</key>
            <string>none</string>
        </dict>

        <!--end customization-->
        <dict>
            <key>include</key>
            <string>source.plsql.oracle</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.plsql.oracle.custom</string>
    <key>uuid</key>
    <string>B0F1D9EB-BB16-4999-8A67-21400A86471C</string>
</dict>
</plist>
