<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>sql</string>
        <string>ddl</string>
        <string>dml</string>
        <string>pks</string>
        <string>pkb</string>
    </array>
    <key>name</key>
    <string>PL/SQL Custom (Oracle)</string>
    <key>patterns</key>
    <array>
        <!--begin customization-->
        <dict>
            <key>match</key>
            <string>(?i)\b(self)\b</string>
            <key>name</key>
            <string>constant.language.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(forall)\b</string>
            <key>name</key>
            <string>keyword.control.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(%(savepoint))\b</string>
            <key>name</key>
            <string>support.function.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b((?<!\.)log)\b</string>
            <key>name</key>
            <string>support.function.builtin.math.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(p(o|io)?_[-a-z0-9_]+)\b</string>
            <key>name</key>
            <string>variable.parameter.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b([lv]_[-a-z0-9_]+)\b</string>
            <key>name</key>
            <string>variable.other.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b((c|gc|k)_[-a-z0-9_]+)\b</string>
            <key>name</key>
            <string>constant.other.oracle</string>
        </dict>
        <!--
        <dict>
            <key>match</key>
            <string>(?i)\b()\b</string>
            <key>name</key>
            <string>keyword.other.oracle</string>
        </dict>
        -->
        <dict>
            <key>match</key>
            <string>(?i)\b(alter(\s+session)?|logging|((global|private)\s+temporary)|on\s+commit\s+(preserve|delete)\s+rows|(authid|bequeath)\s+(current_user|definer)|virtual|invisible|generated\s+(always|by\s+default|on\s+null)\s+as\s+identity|(constructor\s+|static\s+|(map\s+)?member\s+)?(function\s+|procedure\s+)|result|object|body)\b</string>
            <key>name</key>
            <string>keyword.other.ddl.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(to|(public\s+)?synonym|(no)?logging|build\s+(immediate|deferred)|index|dual|within(\s+group)?|errors\s+(into|reject\s+limit)?|truncate)\b</string>
            <key>name</key>
            <string>keyword.other.sql.oracle</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(show\s+errors|off)\b</string>
            <key>name</key>
            <string>keyword.other.sqlplus.oracle</string>
        </dict>
        <!--
        support.class.user-defined.oracle
        support.constant.user-defined.oracle
        support.function.user-defined.oracle
        support.variable.user-defined.oracle
        support.type.user-defined.oracle
        -->
        <dict>
            <!-- Eliminate highlighting of strings beginning wtih "pi_" -->
            <key>match</key>
            <string>(?i)\b(pi_\w+)\b</string>
            <key>name</key>
            <string>support.variable.user-defined.oracle</string>
        </dict>

        <!--end customization-->
        <dict>
            <key>include</key>
            <string>source.plsql.oracle</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.plsql.oracle.custom</string>
    <key>uuid</key>
    <string>B0F1D9EB-BB16-4999-8A67-21400A86471C</string>
</dict>
</plist>
